name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Sync dependencies
        working-directory: personal-site
        run: uv sync --all-extras

      - name: Lint (ruff)
        working-directory: personal-site
        run: uv run ruff check .

      - name: Type-check (mypy)
        working-directory: personal-site
        run: uv run mypy app

      - name: Tests (pytest)
        working-directory: personal-site
        run: uv run pytest

